### ISSUE TITLE
Proteomic-data module update

### ISSUE THREAD

**Issue by zzgeng** [d3b-center/hope-cohort-analysis#59]
A few updates need to be done in `analyses/proteomic-data/`. 

1. Add readme
2. Change the output files name
3. Reform output files, eg remove `old_symbol`. 
4. upload files to s3 `hope_aya/v2` folder

cc @jharenza @JosephDybas

**Comment by jharenza** [comment]
Also may need to rerun without `--explode-records` so we only have the new symbol in output

**Comment by jharenza** [comment]
https://github.com/d3b-center/hope-cohort-analysis/tree/master/analyses/proteomic-data can you add Dan's initial script repo to this readme please @zzgeng ? https://github.com/d3b-center/D3b-DGD-Collaboration/blob/main/scripts/update_gene_symbols.py

**Comment by jharenza** [comment]
closed with #62
