### ISSUE TITLE
V2 data release

### ISSUE THREAD

**Issue by zzgeng** [d3b-center/hope-cohort-analysis#63]
V2 data release 

- [ ] data update
- [ ] rename proteomic data
- [ ] script update
- [ ] re-run the analysis
- [ ] date upload to s3
- [ ] add new analysis 

cc @jharenza

**Comment by jharenza** [comment]
@zzgeng can you also remove 7316-212 from histologies and the methylation matrix for v2.

**Comment by jharenza** [comment]
completed with #40
