### ISSUE TITLE
Modify README file to update analysis modules list and descriptions

### ISSUE THREAD

**Issue by JosephDybas** [d3b-center/hope-cohort-analysis#75]
Include "proteomic-data" in the list of modules and short descriptions

Include a short description for "molecular-subtyping-HGG" module

Include a short description for "tp53_nf1_score" module

Remove the short description for "tmp-calculation" as this does not refer to a module in the analyses list.

**Comment by komalsrathi** [comment]
Hi @JosephDybas I am actually working on re-running my side of the analyses and I have tmb-calculation that will be pushed. If you want, you can remove it in this PR and I can add it back in when I submit my PR. Here is the branch that I am working on: https://github.com/d3b-center/hope-cohort-analysis/tree/rerun-analyses/analyses/tmb-calculation

**Comment by JosephDybas** [comment]
Thanks @komalsrathi I'll do as you suggest and remove it here. You can add it back when you push your analysis.

**Comment by komalsrathi** [comment]
Sounds good!

**Comment by jharenza** [comment]
@zzgeng can you possibly update the readmes?
