### ISSUE TITLE
Update: ALT Analysis

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/hope-cohort-analysis#87]
For the Telomere content vs two age groups colored by Tumor_location:
https://github.com/d3b-center/hope-cohort-analysis/blob/rerun-analyses/analyses/alt-analysis/results/telomere_content_vs_age_two_groups_by_tumor_loc.pdf

Is the p value adjusted with the tumor location? The reason for that question is the fact that midline tumors are mostly in the 0-15 age group so it may bias the ALT telomere content difference

_Originally posted by @mkoptyra in https://github.com/d3b-center/hope-cohort-analysis/issues/77#issuecomment-1870523272_

**Comment by komalsrathi** [comment]
No, If I recall correctly, this was also brought up in our last meeting by @jharenza where she pointed out that coloring by molecular subtype (plot generated by @zzgeng) or tumor location is not going to make any difference to the p-value. I think you said you wanted to just look at the differences visually and keep the plot as is. 

The difference or the p-value is calculated based on the boxes - not the colors. 

If you want the differences between the tumor location, we can create facets by tumor location i.e. for each Tumor location, we will create a comparison between Telomere content vs Age.

**Comment by mkoptyra** [comment]
Could we use some regression tests?

**Comment by komalsrathi** [comment]
1. Boxplot of ALT telomere content vs Age (two groups) faceted by `HOPE_Tumor.Location.condensed`

![image](https://github.com/d3b-center/hope-cohort-analysis/assets/7000615/1f6f77f1-8b30-47eb-9a7d-097064f469f7)

2.  Logistic Regression adjusting for `HOPE_Tumor.Location.condensed`

```
> glm_out <- glm(data = plot_df, formula = t_n_telomere_content ~ age_two_groups + HOPE_Tumor.Location.condensed)
> glm_out <- broom::tidy(glm_out)
> glm_out
# A tibble: 5 × 5
  term                                                        estimate std.error  statistic p.value
  <chr>                                                          <dbl>     <dbl>      <dbl>   <dbl>
1 (Intercept)                                                1.62          0.950  1.70       0.0935
2 age_two_groups[0,15]                                      -0.551         0.392 -1.41       0.164 
3 HOPE_Tumor.Location.condensedCortical                      0.327         0.926  0.354      0.725 
4 HOPE_Tumor.Location.condensedMidline                       0.210         0.949  0.221      0.825 
5 HOPE_Tumor.Location.condensedOther/Multiple locations/NOS  0.0000681     0.942  0.0000722  1.00  
```

cc: @jharenza any suggestions on the regression test? I am confused about the question/goal. The boxplot that I had before (see below) showed difference between Two Age groups vs Telomere content - the p-value has nothing to do with the `HOPE_Tumor.Location.condensed` except the colors.
![Screenshot 2024-01-10 at 2 33 40 PM](https://github.com/d3b-center/hope-cohort-analysis/assets/7000615/290aa4d8-5575-4f38-b419-89dfe6db7366)

**Comment by komalsrathi** [comment]
Closing as no updates on this.
