### ISSUE TITLE
Update: Data availability circos plot

### ISSUE THREAD

**Issue by komalsrathi** [d3b-center/hope-cohort-analysis#88]
Hi Komal; For the data availability circos plot with Tumor location:
https://github.com/d3b-center/hope-cohort-analysis/blob/rerun-analyses/analyses/data-availability/results/hope_clinical_data_availability_age_continuous.pdf

1. Is it possible to integrate the annotation between the rings - (here, below is modification I added in Photoshop with the the annotation on the rings, but ideally the annotations above/between the rings would be ideal)
![hope_clinical_data_availability_age_continuous-MOIDF](https://github.com/d3b-center/hope-cohort-analysis/assets/45633925/f1c21320-92ed-4c7b-ad85-5726aee259f0)

2. the color of the outer age rink. is there a possibility to use a one color changing into another color? We got a feedback that the blue gradient in the peds ring section may be hard to notice any change. Wondering if you have any thoughts about this.

_Originally posted by @mkoptyra in https://github.com/d3b-center/hope-cohort-analysis/issues/77#issuecomment-1870494754_

**Comment by komalsrathi** [comment]
@mkoptyra 

> Is it possible to integrate the annotation between the rings - (here, below is modification I added in Photoshop with the the annotation on the rings, but ideally the annotations above/between the rings would be ideal)

I believe there is no such functionality in the package that I am using so you can continue to add those annotations manually using Photoshop.

> the color of the outer age rink. is there a possibility to use a one color changing into another color? We got a feedback that the blue gradient in the peds ring section may be hard to notice any change. Wondering if you have any thoughts about this.

Yes we could change it to any other color gradient. If you let me know which color you would like to see, I can make the change.

**Comment by mkoptyra** [comment]
Thank you @komalsrathi 
- is there a possibility to separate the rings a little big more soe I can add annotations in Photoshop between?"
- can you try light blue to green option (https://www.schemecolor.com/blue-to-green-gradient.php) ?

**Comment by komalsrathi** [comment]
> is there a possibility to separate the rings a little big more soe I can add annotations in Photoshop between?"

I am trying to do this, but when I separate the rings, the inner white space becomes smaller and annotations are not fitting in so have to reduce their font size - if that is not a problem, I can do it. Or maybe I can try to move the annotations outside?

**Comment by mkoptyra** [comment]
Please try moving it outside?

**Comment by komalsrathi** [comment]
I think it is taking a lot of time on my end to do the formatting so I can do this: 1) Create circos plot in 1 page and legend in 2nd page and you can paste them together in photoshop.

I actually like how it is currently - I don't understand the need to add the legend titles again to each track when it is easily understood from the legends itself. Also the way you have added titles is also ok, not sure why you need to add those titles between each track.

**Comment by jharenza** [comment]
@mkoptyra I think there are two options- heatmap which is horizontal, like an oncoprint, with all labels next to the rows or keep as is - this function isn't really made for this request
