### ISSUE TITLE
Add PXA and Cancer_Group (Expanded abbreviation) column to annotation file

### ISSUE THREAD

**Issue by jharenza** [d3b-center/hope-cohort-analysis#95]
For [this](https://github.com/d3b-center/hope-cohort-analysis/blob/master/analyses/oncoplots/results/annotation_add_tumor_only.txt) file:

1) for Molecular_Subtype == PXA, make Cancer_Group == PXA
2) Add Cancer_Group (Expanded abbreviation) for those in the oncoplot, for eg: (DHG) Diffuse Hemispheric Glioma

cc @mkoptyra

**Comment by komalsrathi** [comment]
Oh okay, I do that within the code, I guess I will make those changes in the annotation file. Thanks for creating this ticket.

**Comment by jharenza** [comment]
No problem- mateusz wanted to hand off this file to the hope folks
